### ISSUE TITLE
10.8 features on 10.7?

### ISSUE THREAD

**Issue by pornel** [servo/core-foundation-rs#109]
I'd like to add a feature to Cargo itself that requires macOS 10.8, but Cargo supports 10.7 as well.

I'm afraid that exposing `kCFURLIsExcludedFromBackupKey` (10.8+) will cause link errors on macOS 10.7.

Can it be linked using `#[linkage = "extern_weak"]`? It seems to be an unstable feature. Is it OK to add `#![feature(linkage)]` to this crate?

**Comment by jdm** [comment]
What about both using weak linkage and hiding the constant (and related attributes) behind a feature? Then Cargo could enable that feature, and anyone not using nightly could leave it disabled.

**Comment by pornel** [comment]
That's a great idea. https://github.com/servo/core-foundation-rs/pull/110
