### ISSUE TITLE
crates.io not updated despite version change

### ISSUE THREAD

**Issue by pornel** [servo/core-foundation-rs#115]
The commit dc4599d8179c01c4a7e1fbcaf73f9ad39891f6d0 with version v0.4.4 was merged  and [passed tests](https://travis-ci.org/servo/core-foundation-rs/builds/262665450), but [crates.io](https://crates.io/crates/core-foundation) still shows 0.4.3.

Did publishing fail, or is it just delayed?

**Comment by jdm** [comment]
Bah, I forgot to pull from master before running cargo publish. Fixed.

**Comment by pornel** [comment]
Thank you
