### ISSUE TITLE
How to use Bookmark Data functions?

### ISSUE THREAD

**Issue by ghost** [servo/core-foundation-rs#116]
Hey there!

I'm interesting in using these functions (and other security-scoped bookmark functions) from a Rust library of mine. What needs to be done in terms of enabling these in this library?

https://github.com/servo/core-foundation-rs/blob/dc4599d8179c01c4a7e1fbcaf73f9ad39891f6d0/core-foundation-sys/src/url.rs#L149-L155

**Comment by jrmuizel** [comment]
It should be as simple as filling out the definitions. You should be able to mostly copy the existing style in that file.

**Comment by atouchet** [comment]
As the question was answered and the original poster deleted their account I am assuming it’s fine to close this.
