### ISSUE TITLE
Add a `TCFType::from_CFType`?

### ISSUE THREAD

**Issue by luser** [servo/core-foundation-rs#140]
I'm writing bindings for spotlight APIs and there are functions like [`MDItemCopyAttribute`](https://developer.apple.com/documentation/coreservices/1427080-mditemcopyattribute?language=objc) that return `CFTypeRef` and it'd be nice to have a safe way to turn that into the concrete type (like `CFString`). If there was something like `fn TCFType::from_CFType(cftype: &CFType) -> Option<Self>` presumably I could write code like:
```rust
let cf_type = unsafe { CFType::wrap_under_get_rule(MDItemCopyAttribute(...)) };
let cf_str = CFString::from_CFType(&cf_type).unwrap();
```

**Comment by faern** [comment]
You can do that with:
```rust
let cf_type = unsafe { CFType::wrap_under_get_rule(MDItemCopyAttribute(...)) };
let cf_str = cf_type.downcast_into<CFString>.unwrap();
```

**Comment by luser** [comment]
Oh great! I was wondering how I missed that, and the answer is "you just implemented it 2 weeks ago":
https://github.com/servo/core-foundation-rs/commit/b13257441d75d0cb715417ebff0381798eaa3dd7#diff-5d90efdad82f0454dea75202c4cddebc

Thanks! :)
