### ISSUE TITLE
Add bindings to control full-screen

### ISSUE THREAD

**Issue by vbo** [servo/core-foundation-rs#203]
I was trying to follow [Implementing the Full-Screen Experience](https://developer.apple.com/library/content/documentation/General/Conceptual/MOSXAppProgrammingGuide/FullScreenApp/FullScreenApp.html) and looks like some of the useful APIs are missing.

E.g. I don't see [NSApplicationPresentationOptions](https://developer.apple.com/documentation/appkit/nsapplicationpresentationoptions?language=objc) which allow things like hiding the dock and controlling cmd+tab behavior. Should we add those?

**Comment by jrmuizel** [comment]
Yes we should.
