### ISSUE TITLE
`TCFType` should require `PartialEq`, `Eq` and `Clone`

### ISSUE THREAD

**Issue by lqf96** [servo/core-foundation-rs#221]
Since `TCFType` trait deals with reference count and `impl_TCFType!` macro already implements `PartialEq`, `Eq` and `Clone` for Core Foundation wrapper types, I propose that trait `TCFType` require these traits to be implemented first and the implementations in `impl_TCFType!` be reordered.

**Comment by jrmuizel** [comment]
This sounds reasonable.

**Comment by lqf96** [comment]
Temporarily closing this, because `PartialEq`, `Eq` and `Clone` currently delegates to `TCFType` implementations. When specialization is fully implemented and stabilized we should only use `impl_TCFType!` macro to implement `TCFType` trait and then implement `PartialEq`, `Eq` and `Clone` for all `TCFType` types.
