### ISSUE TITLE
Release changes since March

### ISSUE THREAD

**Issue by wezm** [servo/core-foundation-rs#339]
The last release was 0.6.4 on Mar 30, 2019. Would be great to get some of the recent changes into a release.

**Comment by jdm** [comment]
Which crate are you talking about? We've definitely released some since then.

**Comment by wezm** [comment]
I was referring to [core-foundation](https://crates.io/crates/core-foundation). It would be great to have a release of `core-text` with my recent changes too though.

**Comment by zubivan** [comment]
Would be great to get a release of `core-graphics` as well.

**Comment by jdm** [comment]
If people submit PRs with cargo.toml version updates for the crates that should be released, I'll merge and publish them.

**Comment by zubivan** [comment]
@jdm bumped CG version to the next minor.

**Comment by jdm** [comment]
Opened #346 for core-foundation, core-foundation-sys, and core-text.

**Comment by atouchet** [comment]
#346 was merged. Can these updates be published to crates.io?

**Comment by jdm** [comment]
I've just published the updates from #349. Is that enough?

**Comment by atouchet** [comment]
I guess so. It would have been nice to include #228 (or better yet an update to 0.8) if you were going to do a breaking change.

**Comment by atouchet** [comment]
There have been new releases of core-foundation, core-text, and core-graphics. I think this should be fine to close now.
