### ISSUE TITLE
core-foundation 0.7.1 breaks semver

### ISSUE THREAD

**Issue by cmyr** [servo/core-foundation-rs#396]
b68e9c782 breaks existing code that is passing by value.

A reasonable fix would be to use `AsRef<T>` in the signatures, which lets code that passes by value continue to compile; or leave it as is and go to 0.8.0?

https://github.com/linebender/piet/pull/220

**Comment by jdm** [comment]
Shoot, I'm not sure how I overlooked that. Thanks!

**Comment by jdm** [comment]
I've yanked 0.7.1; this will be fixed by #397.

**Comment by jneem** [comment]
Now I'm running into problems with [aa6d1cd](https://github.com/servo/core-foundation-rs/commit/aa6d1cd4c15561b48c24322527e3d9e60f603db4), because core-foundation 0.7.0 doesn't build with core-foundation-sys 0.7.1
