### ISSUE TITLE
core-foundation 0.7.0 doesn't build with core-foundation-sys 0.7.1

### ISSUE THREAD

**Issue by jneem** [servo/core-foundation-rs#398]
Sorry for the spam, but since #396 got closed, maybe my comment there got missed: because of [aa6d1cd4c](https://github.com/servo/core-foundation-rs/commit/aa6d1cd4c15561b48c24322527e3d9e60f603db4) core-foundation 0.7.0 doesn't build with core-foundation-sys 0.7.1. I think this means that core-foundation-sys 0.7.1 also needs to be yanked.

**Comment by jdm** [comment]
Thanks for filing this separately. I have yanked core-foundation-sys 0.7.1. Sorry about the mess!

**Comment by jdm** [comment]
Oh wait, I'm reopening this. We need to do a major version bump on core-foundation-sys and stop releasing any more 0.7.x versions.

**Comment by jdm** [comment]
I've yanked 0.7.2, so any use of core-foundation 0.7 should no longer cause any problems.

**Comment by jneem** [comment]
Thanks for the quick fix!
