### ISSUE TITLE
How to NSNumber?

### ISSUE THREAD

**Issue by mikeumus** [servo/core-foundation-rs#476]
For those times: https://developer.apple.com/documentation/imagecapturecore/icdownloadoption/1507789-overwrite

`i8` knows what to do? 👀 

Thanks @jdm 🙇

**Comment by jdm** [comment]
Hmm, looks like we never exposed any bindings that relied on it before. You'll need an [NSNumber trait](https://github.com/servo/core-foundation-rs/blob/ea68a1891a953d2949ee8caf390aad3bb868e904/cocoa-foundation/src/foundation.rs#L298) that `id` [implements](https://github.com/servo/core-foundation-rs/blob/ea68a1891a953d2949ee8caf390aad3bb868e904/cocoa-foundation/src/foundation.rs#L394) and supports whatever [methods](https://developer.apple.com/documentation/foundation/nsnumber?language=objc#topics) you need.

**Comment by jdm** [comment]
Then for the sake of ergonomics, it would make sense to implement the `From<bool>`, `From<i8>`, `From<u8>`, etc. traits as necessary to make creating NSNumbers from Rust primitives easy.

**Comment by mikeumus** [comment]
@jdm so `NSNumber` is a subclass of `NSValue` and not just of type `NSObject` like usual. 

Would this change the trait a little? Maybe this was why it wasn't bound before?

**Comment by jdm** [comment]
Not as far as I know. Every non-primitive shares the same representation.

**Comment by jbis9051** [comment]
Why was this closed?

**Comment by jbis9051** [comment]
In the mean time you can you use use CFNumber functions through 
[Toll-Free Bridging](https://developer.apple.com/library/archive/documentation/General/Conceptual/CocoaEncyclopedia/Toll-FreeBridgin/Toll-FreeBridgin.html#//apple_ref/doc/uid/TP40010810-CH2). For example, I wanted to get the value of a NSNumber, so I used CFNumberGetValue.


```rs
let nsnumber = unsafe { NSDictionary::objectForKey_(nsdictionary, NSString::alloc(nil).init_str("NSScreenNumber")) // this returns an NSNumber};
let mut number: u32 = 0u32;
if !unsafe { CFNumberGetValue(nsnumber as CFNumberRef, kCFNumberIntType,(&mut number) as *mut _ as *mut c_void) } {
       continue;
};

**Comment by mikeumus** [comment]
@jbis9051 it was closed because it was just a question. I have begun an attempt at binding `NSNumber` with little fruit so far:

Happy Holidays @jdm, please see my attempt below.
This is what I added to `./cocoa-foundation/src/foundation.rs`:
``` rust
pub trait NSNumber: Sized {
    unsafe fn init(self) -> id;

    // unsafe fn alloc(_: Self) -> id {
    //     msg_send![class!(NSNumber), alloc]
    // }

    // unsafe fn number(_: Self) -> id {
    //     msg_send![class!(NSNumber), number]
    // }

    unsafe fn initWithBool(self, value: BOOL) -> id;
}

impl NSNumber for id {
    unsafe fn init(self) -> id {
        msg_send![self, init]
    }

    unsafe fn initWithBool(self, value: BOOL) -> id {
        // msg_send![class!(NSNumber), booleanLiteral:value]
        msg_send![self, booleanLiteral:value]
    }

    // unsafe fn objectAtIndex(self, index: NSUInteger) -> id {
    //     msg_send![self, objectAtIndex:index]
    // }
}
```

And this is how I'm calling it in my own project:
``` rust
NSNumber::initWithBool(NSNumber::init(nil), cocoa::base::YES);
```

But it always returns a null pointer: `0x0` even with `YES` or `NO` 🤷🏻‍♂️

_ _ _ 

@jbis9051 I'd love to use your bridge example to produce an `NSNumber`. Is the `CFNumberGetValue` function the one that actually returns an `NSNumber Id Object` ?

Thank you 🙇

**Comment by mikeumus** [comment]
@jbis9051, @jdm 👋🌞, everyone back from the holidays yet? Hope everyone is doing well and healthy. Please see my reply above when/if you get the chance. Thank you 🙇🏻‍♂️

**Comment by jbis9051** [comment]
@mikeumus Not exactly sure what your question is. The docs for CFNumberGetValue can be found [here](https://developer.apple.com/documentation/corefoundation/1543114-cfnumbergetvalue).

**Comment by jdm** [comment]
So `initWithBool` is a message that can only be sent to an existing NSNumber value. You're looking for `numberWithBool` instead, which should be something like this:
```rust
msg_send![class!(NSNumber), numberWithBool:value]
```
