### ISSUE TITLE
Publish cocoa-rs?

### ISSUE THREAD

**Issue by WalrusSoup** [servo/core-foundation-rs#504]
It looks like [cocoa-rs](https://crates.io/crates/cocoa/0.24.0) is still on `0.24.0` so this [pull request](https://github.com/servo/core-foundation-rs/pull/456) adding support for `runningApplicationWithProcessIdentifier` is missing. Any chance we could get an update out?

**Comment by jrmuizel** [comment]
Can you write a PR bumping the version?

**Comment by WalrusSoup** [comment]
@jrmuizel  PR is ready. Closing this to move discussion into PR if needed.
