### ISSUE TITLE
Publish new version to crates.io

### ISSUE THREAD

**Issue by MatrixDev** [servo/core-foundation-rs#520]
I know this repository sometimes merges new PRs, but the latest version (cocoa or cocoa-foundation) on the crates.io was published 2 years ago and doesn't contain those changes.

**Comment by WalrusSoup** [comment]
I think it just needs to be tagged for Crates to get it?

**Comment by jrmuizel** [comment]
I published cocoa but don't have permissions to publish cocoa-foundation. @jdm can you add me or servo as an owner for cocoa-foundation?

**Comment by jdm** [comment]
That's odd—you're a member of the `servo/cargo publish` team which is an owner of https://crates.io/crates/core-foundation.

**Comment by jrmuizel** [comment]
[cocoa-foundation](https://crates.io/crates/cocoa-foundation) not core-foundation

**Comment by jdm** [comment]
Whoops. That has now been fixed!

**Comment by diceride** [comment]
@jrmuizel It would be nice if you could publish the latest version. Thank you.

**Comment by alex** [comment]
I'd be grateful for a release of core-foundation-sys: I'm interested in getting https://github.com/servo/core-foundation-rs/pull/502 into my build to improve build times. Thanks much!

**Comment by atouchet** [comment]
This was done.
