### ISSUE TITLE
core-graphics requires core-foundation 0.9.3 for mach_port

### ISSUE THREAD

**Issue by simonbuchan** [servo/core-foundation-rs#530]
Just hit this build error when I added `wry` to my app:

```
error[E0432]: unresolved import `core_foundation::mach_port`
 --> /Users/adamfreeman/.cargo/registry/src/github.com-1ecc6299db9ec823/core-graphics-0.22.3/src/event.rs:4:5
  |
4 |     mach_port::{CFMachPort, CFMachPortRef},
  |     ^^^^^^^^^ could not find `mach_port` in `core_foundation`

error[E0433]: failed to resolve: could not find `mach_port` in `core_foundation`
  --> /Users/adamfreeman/.cargo/registry/src/github.com-1ecc6299db9ec823/core-graphics-0.22.3/src/sys.rs:32:44
   |
32 |     pub type CGEventTapRef = core_foundation::mach_port::CFMachPortRef;
   |                                               ^^^^^^^^^ could not find `mach_port` in `core_foundation`
```

trivial MR to fix this one, just update the dependency to `0.9.2` or `0.9.3`, but there's probably more like this, and it may be worth adding something like https://crates.io/crates/cargo-minimal-versions to the CI to catch these in the future.

**Comment by simonbuchan** [comment]
Note the local workaround is simply: `cargo update -p core-foundation`, so this isn't a huge deal!

**Comment by waywardmonkeys** [comment]
This is no longer an issue as core-graphics is now at 0.24 and depends on core-foundation 0.10.
