### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by GuillaumeGomez** [servo/core-foundation-rs#617]
Hi. A lot of new items (which I need) were added to the crate since the last release. Do you know when the next release will be? Also, if there are still some work to be done, how can I help?

Thanks in advance!

**Comment by jrmuizel** [comment]
Which things were added that you need?

**Comment by GuillaumeGomez** [comment]
`CFStringCreateWithCStringNoCopy`.

**Comment by GuillaumeGomez** [comment]
Thanks a lot!

**Comment by GuillaumeGomez** [comment]
You didn't apparently: https://crates.io/crates/core-foundation-sys ?

**Comment by jrmuizel** [comment]
I ended up having to yank it because of #619

**Comment by GuillaumeGomez** [comment]
Oh I see. Well, waiting for next one then. :)
