### ISSUE TITLE
Publish a new version of cocoa-foundation

### ISSUE THREAD

**Issue by afranchuk** [servo/core-foundation-rs#634]
The `cocoa-foundation` crate had some unnecessary (and duplicate/inconsistent wrt other crates) versions of the `foreign-types` dependency, which has since been removed. However, no new version has been published, and e.g. using `cocoa 0.25` depends on both `foreign-types 0.3` and `foreign-types 0.5`. Publishing a new version of cocoa-foundation would avoid this problem.

**Comment by jrmuizel** [comment]
Done
