### ISSUE TITLE
ScreenCaptureAccess.preflight returns incorrect value for Intel based 64bit Mac

### ISSUE THREAD

**Issue by Pranav2612000** [servo/core-foundation-rs#677]
The function ScreenCaptureAccess.preflight [ [Ref](https://github.com/servo/core-foundation-rs/blob/e5162be4fa50c9f7f2f41f1d310eb49268c4e88e/core-graphics/src/access.rs#L17) ] returns incorrectly for Intel based 64 bit Macs.

On further inspection, the reason for this is that the external method `CGPreflightScreenCaptureAccess` returns a value which is not 1 ( even if the permissions have been given ). 
From my research, I've found that it returns a number whose lowest 8 bits are 0. So something like the following should work

<img width="609" alt="image" src="https://github.com/servo/core-foundation-rs/assets/20909078/4e448c9e-9797-4f0d-8d20-168316966bda">

That's what I'm doing in my fork [here](https://github.com/Pranav2612000/core-foundation-rs)

This is working good enough for me. What do you think about this approach? Does it make sense? I'm open to submitting a PR, or if you have a better solution in mind, I'll love to implement it.

**Comment by madsmtm** [comment]
The correct way to work with external booleans is always to compare them against `NO` / `0`. So rather, you should use `!= 0`

**Comment by Pranav2612000** [comment]
Yup @madsmtm . That was what I tried first, but I observed that `CGPreflightScreenCaptureAccess` returns a non zero value ( the last 8 bits of which are 0 ) if screen capture permissions are not present. So the function would always return true, which is not the correct behaviour.

Is it possible that it's something to do with Boolean being 1 byte by int32 being 4 bytes? Because the last 8 bits of the returned value are always 0000 0000 or 0000 0001

**Comment by Pranav2612000** [comment]
Yup. Thank you @madsmtm 
What do you think the next steps should be here? Happy to submit a PR

**Comment by madsmtm** [comment]
Can't answer that, not a maintainer here, sorry

**Comment by jrmuizel** [comment]
Please submit a PR

**Comment by waywardmonkeys** [comment]
I've doe what @madsmtm suggested as the fix (after verifying in the SDK headers) in #698.
