### ISSUE TITLE
core-graphics: non-public API usage _CGContextSetFontSmoothingStyle

### ISSUE THREAD

**Issue by lucasfernog-crabnebula** [servo/core-foundation-rs#707]
I'm trying to submit an iOS app but Apple is rejecting it:
```
ITMS-90338: Non-public API usage - The app references non-public symbols in <appName>: _CGContextSetFontSmoothingStyle. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/
```

Even though my dependencies do not use the `set_font_smoothing_style` API, seems like Rust cannot strip it.

Similar to #656

I thought about deleting the API similar to  #700 but seems like at least alacritty uses it. Maybe it makes sense to use a feature flag instead?

**Comment by waywardmonkeys** [comment]
Are you sure that alacrity is using it and if so, through core_graphics?

**Comment by lucasfernog-crabnebula** [comment]
oh nvm they have their own bindings it seems https://github.com/search?q=set_font_smoothing_style&type=code

**Comment by lucasfernog-crabnebula** [comment]
I guess we could follow that other PR and remove the API instead..

**Comment by waywardmonkeys** [comment]
And those are old forks… pretty sure the code is gone from current alacritty.

**Comment by waywardmonkeys** [comment]
> I guess we could follow that other PR and remove the API instead..

I think I prefer this. If someone needs it, they can do a local binding… and GitHub search doesn’t seem to turn up users.

**Comment by lucasfernog-crabnebula** [comment]
Alright I've opened a new PR.. let me know if there's anything else I can do.. this makes it impossible to ship any app to App Store :( and if this is released as 0.25 (it should right?) then it'll take some time to propagate this change to the ecosystem.

**Comment by jdm** [comment]
You should be able to rely on a fork with the 0.24 version and a cargo patch to override other copies in the ecosystem until that's complete.

**Comment by lucasfernog** [comment]
that's what i'm doing for now - but i need to instruct Tauri users to do the same

**Comment by lucasfernog** [comment]
thanks for the feedback and quick response btw!

**Comment by atouchet** [comment]
Done in #709.
