### ISSUE TITLE
Stop using links

### ISSUE THREAD

**Issue by nox** [servo/core-foundation-rs#97]
AFAIK, the `links` attribute in Cargo only exist because on some platforms, linking multiple times to a single thing is a recipe for failure. I don't think that is the case for macOS frameworks, and having Cargo fail because two core-foundation-sys versions are used in a single project is a PITA (see #96).

We should probably not use `links` if we can afford to make do without it.

Cc @tomaka for the initial paper cut, @alexcrichton for his Cargo knowledge and to confirm or infirm what I just wrote.

**Comment by tomaka** [comment]
`links` should just die in a fire.

**Comment by alexcrichton** [comment]
The purpose of `links` is to prevent two different versions of the same native library from being linked into a process, as this is basically guaranteed to never work. Libraries like libgit2-sys vendor different versions of libgit2 over time, and hence rely on this to provider a nicer error message than an accidental segfault.

Crates which link to system libraries, like this one, tend to always link dynamically and the system library itself does not change versions over time. In that sense it's unlikely to cause issues if there's two versions of this crate linked into the same project. As a result of that, yes `links` should be ok to remove here.
